version: '3'

services:
  database:
    image: 'postgres:latest'
    container_name: PostgresDB
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: JavaModularity
