
name: Star Count



on:
  workflow_dispatch:
  
  issues:
    types:
      - opened
  workflow_call:
    outputs:
      stars:
       value: ${{jobs.job.outputs.stars}}
  
jobs:
  job:
    outputs:
      stars: ${{steps.repo-stars.outputs.stars}}
    runs-on: ubuntu-latest
    steps:
      - name: Repo Star Count
        id: repo-stars
        uses: alanhg/repo-star-count-action@master
