
name: Star Count

on:
  workflow_dispatch:
  
  issues:
    types:
      - opened

jobs:
  job:
    outputs:
      output1: ${{steps.repo-stars.outputs.stars}}
    runs-on: ubuntu-latest
    steps:
      - name: Repo Star Count
        id: repo-stars
        uses: alanhg/repo-star-count-action@master
